language: java
notifications:
  email: false
jdk:
- oraclejdk8
before_deploy:
    - "mvn versions:set -DnewVersion=$TRAVIS_BUILD_NUMBER"
    - "mvn versions:commit"
deploy:
  provider: bintray
  file: bintray-descriptor
  user: wazim
  key: e0ddb1e0d30976f3d2d37ec2ab62014029c235ed
