language: java
notifications:
  email: false
jdk:
- oraclejdk8
after_success:
- mvn versions:set -DnewVersion=$TRAVIS_BUILD_NUMBER
- mvn versions:commit
- mvn install -DskipTests=true
- curl -v -T /home/travis/build/wazim/pitstop/target/pitstop-$TRAVIS_BUILD_NUMBER.jar -u $BINTRAY_USER:$BINTRAY_PASSWORD https://api.bintray.com/maven/wazim/maven/pitstop/net/wazim/pitstop/$TRAVIS_BUILD_NUMBER/pitstop-$TRAVIS_BUILD_NUMBER.jar?publish=1